version: '2'
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx
    links:
      - nexus:nexus
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf.tpl:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
     - nexus
  nexus:
    image: sonatype/nexus3:3.14.0
    container_name: nexus
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 8084:8084
    volumes:
      - /root/nexus/nexus-data:/nexus-data
      - /root/nexus/ssl:/opt/sonatype/nexus/etc/ssl
